#!/usr/bin/env python3
"""Git commit-msg hook: strip any Cursor co-author trailer before committing."""
import re, sys
msg = open(sys.argv[1]).read()
msg = re.sub(r'\nCo-authored-by: Cursor <cursoragent@cursor\.com>', '', msg)
msg = msg.rstrip() + '\n'
open(sys.argv[1], 'w').write(msg)
